# -*- coding: utf-8 -*-
"""level2_task 2_Time Series Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YxZvr3mtu8Yfsgy7Q6WR9LzTzoa5gRa2

**Level 2 – Task 2: Time Series Analysis**
"""

# STEP 1 – Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.tsa.seasonal import seasonal_decompose

sns.set(style="whitegrid")

# STEP 2 – Load Dataset
df = pd.read_csv("/content/2) Stock Prices Data Set.csv")
df.head()

# STEP 3 – Check Columns (Important)
df.columns

df.info()

# STEP 4 – Clean Column Names (Safe Practice)
df.columns = df.columns.str.strip()

# STEP 5 – Convert Date Column (Very Important Step)
df['date'] =pd.to_datetime(df['date'], errors="coerce")

df['date'].head()

# STEP 6 – Drop Null Dates
df = df.dropna(subset=['date'])

# STEP 7 – Convert Close to Numeric
df['close'] = pd.to_numeric(df['close'], errors="coerce")
df = df.dropna(subset=['close'])

# STEP 8 – Sort by Date
df = df.sort_values('date')

df

# STEP 9 – Set Date as Index (MOST IMPORTANT)
df.set_index('date', inplace=True)

# STEP 10 – Confirm Index is Datetime
print(type(df.index))

print(df.index[:5])

# STEP 11 – Now Plot Time Series
plt.figure(figsize=(12, 6))
plt.plot(df.index, df['close'])
plt.title("Stock Closing Price Over Time")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.show()

# STEP 12 – Moving Average (30-Day)
df['30_MA'] = df['close'].rolling(window=30).mean()

plt.figure(figsize=(12,6))
plt.plot(df['close'], label="Original")
plt.plot(df['30_MA'], label="30-Day Moving Average", color='red')
plt.legend()
plt.title("Moving Average Smoothing")
plt.show()

# STEP 13 – Set Proper Frequency
df = df.asfreq('D')
df['close'] = df['close'].fillna(method='ffill')

# STEP 14 – Decomposition
decomposition = seasonal_decompose(df['close'], model='additive', period=30)

decomposition.plot()
plt.show()