# -*- coding: utf-8 -*-
"""Level1_Task1_Data_Cleaning_and_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15hqROWjA33-kMI2DDjZlSRkEt9zZd-Rj

**📘 Level 1 – Task 1: Data Cleaning and Preprocessing**

Step-by-Step Implementation
"""

# Step 1: Import Required Library
import pandas as pd

# Step 2: Load the Dataset
df = pd.read_csv("churn-bigml-80.csv")
df.head()

# Step 3: Understand Dataset Structure
df.info()

df.shape

# Step 4: Identify Missing Values
df.isnull()

df.isnull().sum()

# Step 5: Check and Remove Duplicate Records
df.duplicated().sum()

df.drop_duplicates(inplace=True)

# Step 6: Standardize Categorical Data
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
  df[col] = df[col].str.lower().str.strip()

print(categorical_cols)

# Step 7: Convert Boolean Columns
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

print(bool_cols)

# Step 8: Final Verification
df.isnull().sum()

df.info()

# Save cleaned dataset into CSV file

df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")