# -*- coding: utf-8 -*-
"""level1_task1_Exploratory_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SF1AFqSyqTt4zrl0eG7ZDSAKKGCkpQOZ

**Task 2: Exploratory Data Analysis
(EDA)**
"""

# STEP 1: Import Required Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# STEP 2: Load Dataset
df = pd.read_csv("cleaned_dataset.csv")
# view first 5 rows
df.head()

# STEP 3: Basic Dataset Information
df.shape

df.info()

df.describe()

# STEP 4: Summary Statistics Manually Calculate
# Mean
print("Average:")
df.mean(numeric_only=True)

# Median
print("Median:")
df.median(numeric_only=True)

# Mode
print("Mode: ")
df.mode(numeric_only=True)

# Standard Deviation
print("Standard Deviation: ")
df.std(numeric_only=True)

# STEP 5: Histogram (Distribution Check)
# Example – Total Day Minutes
plt.figure()
sns.histplot(df['Total day minutes'], kde=True)
plt.title("Distribution of Total Day Minutes")
plt.show()

# STEP 6: Boxplot (Outlier Detection)
plt.figure()
sns.boxplot(x=df['Total day charge'])
plt.title("Boxplot of Total Day Charge")
plt.show()

# STEP 7: Scatter Plot (Relationship Check)
# Example – Day Minutes vs Day Charge
plt.figure()
sns.scatterplot(x=df['Total day minutes'], y=df['Total day charge'])
plt.title("Total Day Minutes vs Total Day Charge")
plt.show()

plt.figure(figsize=(12,10))

numeric_df = df.select_dtypes(include=['int64', 'float64'])

sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", fmt=".2f")

plt.title("Correlation Matrix")
plt.show()

# STEP 9: Churn Analysis (Important Insight)
sns.countplot(x=df['Churn'])
plt.title("Churn Distribution")
plt.show()