# -*- coding: utf-8 -*-
"""Level 3_Task 1_Predictive Modeling (Classification).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I_iCmXsXYl0l3bSaeRsygdgr2r8wyJlk

**Level 3 – Task 1: Predictive Modeling (Classification)**

Dataset: churn-bigml-80.csv
"""

# STEP 1 – Import Required Libraries
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning utilities
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Classification models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Model evaluation metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Hyperparameter tuning
from sklearn.model_selection import GridSearchCV

# STEP 2 – Load Dataset
# Load Dataset
df = pd.read_csv("/content/churn-bigml-80.csv")

# Display first 5 rows
df.head()

# STEP 3 – Explore Dataset
# Check structure of dataset
df.info()

# Check statistical summary
df.describe()

# Check missing values
df.isnull().sum()

# STEP 4 – Handle Categorical Variables
# Dataset madhe categorical columns aahet:

# State

# International plan

# Voice mail plan

# Initialize label encoder
le = LabelEncoder()

# Convert categorical variables to numeric
df['International plan'] = le.fit_transform(df['International plan'])
df['Voice mail plan'] = le.fit_transform(df['Voice mail plan'])
df['State'] = le.fit_transform(df['State'])

# STEP 5 – Define Features and Target
# Target variable
y = df['Churn']

# Feature variables
X = df.drop('Churn', axis=1)

# STEP 6 – Split Dataset (Train/Test)
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# STEP 7 – Feature Scaling
# Distance-based models better perform with scaling.
# Initialize scaler
scaler = StandardScaler()

# Fit on training data
X_train = scaler.fit_transform(X_train)

# Transform testing data
X_test = scaler.transform(X_test)

# STEP 8 – Logistic Regression Model
# Create Logistic Regression model
log_model = LogisticRegression()

# Train model
log_model.fit(X_train, y_train)

# Make predictions
y_pred_log = log_model.predict(X_test)

# STEP 9 – Evaluate Logistic Regression
print("Logistic Regression Performance")

print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Precision:", precision_score(y_test, y_pred_log))
print("Recall:", recall_score(y_test, y_pred_log))
print("F1 Score:", f1_score(y_test, y_pred_log))

# STEP 10 – Decision Tree Model
# Initialize Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)

# Train model
dt_model.fit(X_train, y_train)

# Predictions
y_pred_dt = dt_model.predict(X_test)

# STEP 11 – Evaluate Decision Tree
print("Decision Tree Performance")

print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall:", recall_score(y_test, y_pred_dt))
print("F1 Score:", f1_score(y_test, y_pred_dt))

# STEP 12 – Random Forest Model
# Initialize Random Forest model
rf_model = RandomForestClassifier(random_state=42)

# Train model
rf_model.fit(X_train, y_train)

# Predictions
y_pred_rf = rf_model.predict(X_test)

# STEP 13 – Evaluate Random Forest
print("Random Forest Performance")

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))

# STEP 14 – Hyperparameter Tuning (Grid Search)
# Define parameter grid
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [5, 10, None]
}

# Initialize GridSearch
grid_search = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=5
)

# Train grid search
grid_search.fit(X_train, y_train)

# Display best parameters
print("Best Parameters:", grid_search.best_params_)