# -*- coding: utf-8 -*-
"""Level2_Task3_Clustering Analysis (KMeans)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3a-ErvK0zT2RFf2gmQByut4Ec_zHwqK

Level2_Task3_Clustering Analysis (KMeans)
"""

# STEP 1 – Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# STEP 2 – Load Dataset
df = pd.read_csv('/content/1) iris.csv')

df.head()

# STEP 3 – Check Dataset
df.info()

df.describe()

# STEP 4 – Select Features
x = df.iloc[:, 0:4]

# STEP 5 – Standardize Data
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# STEP 6 – Elbow Method (Find Optimal K)
inertia = []

K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(x_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(K_range, inertia, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.show()

# STEP 7 – Apply KMeans (K=3)
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(x_scaled)

df['Cluster'] = clusters

# STEP 8 – Visualize Clusters (2D Plot)
plt.figure(figsize=(8,6))
sns.scatterplot(
    x=df['petal_length'],
    y=df['petal_width'],
    hue=df['Cluster'],
    palette='Set1'
)
plt.title("KMeans Clustering on Iris Dataset")
plt.show()

sns.pairplot(df, hue='Cluster')